import { StyleSheet } from 'react-native'
import { Colors } from './colors'

export const Typography = StyleSheet.create({
  heading1: {
    fontSize: 48,
    lineHeight: 52,
    fontFamily: 'Nunito-Bold',
    color: Colors.gray95,
  },
  heading2: {
    fontSize: 40,
    lineHeight: 44,
    fontFamily: 'Nunito-Bold',
    color: Colors.gray95,
  },
  heading3: {
    fontSize: 32,
    lineHeight: 36,
    fontFamily: 'Nunito-Bold',
    color: Colors.gray95,
  },
  heading4: {
    fontSize: 24,
    lineHeight: 28,
    fontFamily: 'Nunito-Bold',
    color: Colors.gray95,
  },
  heading5: {
    fontSize: 20,
    lineHeight: 24,
    fontFamily: 'Nunito-Bold',
    color: Colors.gray95,
  },
  heading6: {
    fontSize: 18,
    lineHeight: 22,
    fontFamily: 'Nunito-Bold',
    color: Colors.gray95,
  },
  body18Bold: {
    fontSize: 18,
    lineHeight: 24,
    fontFamily: 'Nunito-Bold',
    letterSpacing: 0.1,
    fontWeight: '700',
    color: Colors.gray95,
  },
  body18SemiBold: {
    fontSize: 18,
    lineHeight: 24,
    fontFamily: 'Nunito-SemiBold',
    fontWeight: '600',
    letterSpacing: 0.1,
    color: Colors.gray95,
  },
  body18Medium: {
    fontSize: 18,
    lineHeight: 24,
    fontFamily: 'Nunito-Medium',
    letterSpacing: 0.1,
    fontWeight: '500',
    color: Colors.gray95,
  },
  body18Normal: {
    fontSize: 18,
    lineHeight: 24,
    fontFamily: 'Nunito-Regular',
    letterSpacing: 0.1,
    color: Colors.gray95,
  },
  body16Bold: {
    fontSize: 16,
    lineHeight: 22,
    fontFamily: 'Nunito-Bold',
    letterSpacing: 0.1,
    fontWeight: '700',
    color: Colors.gray95,
  },
  body16SemiBold: {
    fontSize: 16,
    lineHeight: 22,
    fontFamily: 'Nunito-SemiBold',
    letterSpacing: 0.1,
    fontWeight: '600',
    color: Colors.gray95,
  },
  body16Medium: {
    fontSize: 16,
    lineHeight: 22,
    fontFamily: 'Nunito-Medium',
    letterSpacing: 0.1,
    color: Colors.gray95,
    fontWeight: '500',
  },
  body16Normal: {
    fontSize: 16,
    lineHeight: 22,
    fontFamily: 'Nunito-Regular',
    letterSpacing: 0.1,
    color: Colors.gray95,
    fontWeight: '400',
  },
  body15Bold: {
    fontSize: 15,
    lineHeight: 22,
    fontFamily: 'Nunito-Bold',
    letterSpacing: 0.1,
    color: Colors.gray95,
    fontWeight: '700',
  },
  body15SemiBold: {
    fontSize: 15,
    lineHeight: 22,
    fontFamily: 'Nunito-SemiBold',
    letterSpacing: 0.1,
    color: Colors.gray95,
    fontWeight: '600',
  },
  body15Medium: {
    fontSize: 15,
    lineHeight: 22,
    fontFamily: 'Nunito-Medium',
    letterSpacing: 0.1,
    color: Colors.gray95,
  },
  body15Normal: {
    fontSize: 15,
    lineHeight: 22,
    fontFamily: 'Nunito-Regular',
    color: Colors.gray95,
  },
  body14Bold: {
    fontSize: 14,
    lineHeight: 20,
    fontFamily: 'Nunito-Bold',
    letterSpacing: 0.1,
    color: Colors.gray95,
    fontWeight: '700',
  },
  body14ExtraBold: {
    fontSize: 14,
    lineHeight: 20,
    fontFamily: 'Nunito-ExtraBold',
    letterSpacing: 0.1,
    color: Colors.gray95,
    fontWeight: '700',
  },
  body14SemiBold: {
    fontSize: 14,
    lineHeight: 20,
    fontFamily: 'Nunito-SemiBold',
    letterSpacing: 0.1,
    color: Colors.gray95,
    fontWeight: '600',
  },
  body14Medium: {
    fontSize: 14,
    lineHeight: 20,
    fontFamily: 'Nunito-Medium',
    letterSpacing: 0.1,
    color: Colors.gray95,
  },
  body14Normal: {
    fontSize: 14,
    lineHeight: 20,
    fontFamily: 'Nunito-Regular',
    letterSpacing: 0.1,
    color: Colors.gray95,
  },
  body13Bold: {
    fontSize: 13,
    lineHeight: 18,
    fontFamily: 'Nunito-Bold',
    letterSpacing: 0.1,
    color: Colors.gray95,
    fontWeight: '700',
  },
  body13SemiBold: {
    fontSize: 13,
    lineHeight: 18,
    fontFamily: 'Nunito-SemiBold',
    letterSpacing: 0.1,
    color: Colors.gray95,
    fontWeight: '600',
  },
  body13Medium: {
    fontSize: 13,
    lineHeight: 18,
    fontFamily: 'Nunito-Medium',
    letterSpacing: 0.1,
    color: Colors.gray95,
  },
  body13Normal: {
    fontSize: 13,
    lineHeight: 18,
    fontFamily: 'Nunito-Regular',
    letterSpacing: 0.1,
    color: Colors.gray95,
  },
  body12Bold: {
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 0.1,
    fontFamily: 'Nunito-Bold',
    color: Colors.gray95,
  },
  body12SemiBold: {
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 0.1,
    fontFamily: 'Nunito-SemiBold',
    color: Colors.gray95,
    fontWeight: '600',
  },
  body12Medium: {
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 0.1,
    fontFamily: 'Nunito-Medium',
    color: Colors.gray95,
  },
  body12Normal: {
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 0.1,
    fontFamily: 'Nunito-Regular',
    fontWeight: '400',
    color: Colors.gray95,
  },
  body10Bold: {
    fontSize: 10,
    lineHeight: 14,
    letterSpacing: 0.1,
    fontFamily: 'Nunito-Bold',
    color: Colors.gray95,
  },
  body10SemiBold: {
    fontSize: 10,
    lineHeight: 14,
    letterSpacing: 0.1,
    fontFamily: 'Nunito-SemiBold',
    color: Colors.gray95,
  },
  body10Medium: {
    fontSize: 10,
    lineHeight: 14,
    letterSpacing: 0.1,
    fontFamily: 'Nunito-Medium',
    color: Colors.gray95,
  },
  body10Normal: {
    fontSize: 10,
    lineHeight: 14,
    letterSpacing: 0.1,
    fontFamily: 'Nunito-Regular',
    color: Colors.gray95,
  },
})
